from abc import ABC,abstractmethod
class BenchmarkModel(ABC):
    @property
    @abstractmethod
    def name(self):...
    @abstractmethod
    def prepare(self):...
    @abstractmethod
    def train(self):...
    @abstractmethod
    def predict(self):...
    @abstractmethod
    def evaluate(self):...
