from abc import ABC,abstractmethod
class BenchmarkModel(ABC):
    @property
    @abstractmethod
    def name(self):...
    @abstractmethod
    def prepare(self):...
    @abstractmethod
    def train(self):...
    @abstractmethod
    def predict(self):...
    @abstractmethod
    def evaluate(self):...
    @abstractmethod
    def benchmark_metadata(self):
        """Return backend identity and training settings for result logging."""
        ...
    def parameter_count(self):
        return None
